### ISSUE TITLE
Identical id custom categories of the store.

### ISSUE THREAD

**Issue by hiromant** [davidtsadler/ebay-sdk-php#101]
I get categories from the ebay store. But all custom categories have the same id.
Why are the id categories identical?
How to get different id categories?
Screenshot: [https://i.imgur.com/gFDEzdd.png](url)

**Comment by davidtsadler** [comment]
It looks like you are using a 32 bit version of PHP.  This means that the largest possible integer value is 2147483647. Since eBay will return category IDs that are larger, for example 51874727017, you are going to have to switch to a 64 bit version of PHP as [documented in the requirements](http://devbay.net/sdk/guides/getting-started/requirements.html#using-the-sdk-with-32-bit-systems) for the SDK.

**Comment by hiromant** [comment]
Thanks for help :)

**Comment by medigeek** [comment]
@davidtsadler Would be nice to have an informative error about this issue. Thank you for all your work so far! :)
