### ISSUE TITLE
missing shipping service code type: FedExGroundInternationalToCanada

### ISSUE THREAD

**Issue by jlahijani** [davidtsadler/ebay-sdk-php#104]
When creating a listing on eBay, "FedEx Ground International to Canada" is an available option (FedExGroundInternationalToCanada).  It is not listed in the code however:

ebay-sdk-php\src\Trading\Enums\ShippingServiceCodeType.php

**Comment by davidtsadler** [comment]
The SDK is generated from the WSDL's that are provided by eBay. The same WSDL's that eBay use to generate the [list of services](https://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ShippingServiceCodeType.html) in the documentation. The complete list of services is not available through the WSDL's because they can change overtime. You instead have to regularly call [GeteBayDetails](https://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GeteBayDetails.html) which will return all possible values.
