### ISSUE TITLE
sockect connect can't be release

### ISSUE THREAD

**Issue by legend-goat** [davidtsadler/ebay-sdk-php#149]
I used the method \DTS\eBaySDK\Trading\Services::getMyeBaySelling
 
After php shell run 30 minutes, the process is waiting, The Service message :" socket can't identify protocol "

my program segment as follows:

> $pageNum = 1;
>         do {
>             $request->ActiveList->Pagination->PageNumber = $pageNum;
>             $response = $service->getMyeBaySelling($request);
>             $this->_handleResponse($response, $accountSn, $siteId, $pageNum);
>             $pageNum += 1;
>         } while (isset($response->ActiveList) && $pageNum <= $response->ActiveList->PaginationResult->TotalNumberOfPages);
>

**Comment by michabbb** [comment]
can you ping the ebay server (you are talking to) ? 
are you able to make connections with telnet or postman ?
if you try sandbox, check if you have the same problem with live.

**Comment by Stone-Ynn** [comment]
This shell run in production environment.  ping the ebay server is ok.
if getMyeBaySelling is right, the socekt should close. 
In my program, i have 1000 ebay accounts,  
use the following 1000 times
> $service = new Services\TradingService([ 'credentials' => $this->credentials, 'siteId' => $siteId]);

i wonder the socket doesn't close after getMyeBaySelling.

**Comment by Stone-Ynn** [comment]
Catching Exception：

>  cURL error 7: Failed to connect to api.ebay.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
> cURL error 7: Failed to connect to api.ebay.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
> cURL error 7: Failed to connect to api.ebay.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
> cURL error 7: Failed to connect to api.ebay.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
> cURL error 7: Failed to connect to api.ebay.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
> cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

cUrl error 7 ,Failed 5 times, and 5 sockets can't identify protocol in Centos6.x.
then the process is stop and waiting, can't be exit.

**Comment by Stone-Ynn** [comment]
while catch the curl error exception, can i close the connect? And then the process continue.

**Comment by davidtsadler** [comment]
From bitter experience I have had some eBay operations take anything from 20 seconds to a minute to return data from a seller. From the errors it looks like cURL is timing out. By default it will only wait for a few seconds. If there is no response in that time it gives up. You could try setting the [connect_timeout](http://devbay.net/sdk/guides/guide/configuration.html#connect-timeout) configuration option to zero to tell cURL to wait indefinitely.

**Comment by Stone-Ynn** [comment]
if I set the otion to zero, my process is waiting ,but i want run the nest task. 

i don't know what cased this error, and my process is waiting.
> cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by Stone-Ynn** [comment]
At this time, my process stop,  "socket can't identify protocol" at my service , centos 6.x

**Comment by davidtsadler** [comment]
Have to admit I'm a bit stumped at the moment so not sure what to advise,

**Comment by Stone-Ynn** [comment]
i have 100 ebay accounts, get ebay data used one process. while i wait the ebay response,the process is waiting , my next account can't get data.

**Comment by Stone-Ynn** [comment]
while a large number of  Connection timed out, the sock fd don't close, this can caused 'socket can't identify protocol', and the process is waiting.
I have no idea, how to solve this problem? who can give me a advise?

**Comment by michabbb** [comment]
@Stone-Ynn a connection is based of two partners, and there will be one partner in this relation you don´t and never will have influence of: ebay. curl connection problems are not related to this SDK, because guzzle uses curl and curl errors is a connection problem, not a SDK problem.

you just have to deal with the situation, that your api (doesn´t matter which api we are talking about) is down, not responding, is configured wrong, brings timeouts, whatever.... *you* have to deal with that and find ways to handle this:

- catch timeouts
- catch host not reachable
- retry calls
- catch everything else

it sounds like your jobs are handled sequential, hard to believe for somebody who is dealing with 100 ebay accounts, thats a lot. so you must manage 100k of ebay items. with this mass of items you should
think about handling all jobs in parallel. and you should use a queue, so if a jobs fails, it does not affect any other jobs and it´s easy to implement a "redo" functionality. of course these are workarrounds, but needed if you have to deal with millions of calls by month/week.

for debugging your tcp problems: use a different server, OS, hoster, just to be able to compare.
if you use virtualization software: don´t use it. make tests with total different ENV.
