### ISSUE TITLE
Auto fill HDR_API_VERSION if apiVersion not set

### ISSUE THREAD

**Issue by dtjones** [davidtsadler/ebay-sdk-php#15]
Would it be possible to add a constant to each service which holds the current supported API version. 
Like so. 
e.g 

    class TradingBaseService extends \DTS\eBaySDK\Services\BaseService
    {
        /**
         * Constants for the various HTTP headers required by the API.
         */
        const API_VERSION = 947;
        const HDR_API_VERSION = 'X-EBAY-API-COMPATIBILITY-LEVEL';

Then if an apiVersion is required but not supplied then the constant can be used 

        if ($this->getConfig('apiVersion')) {
            $headers[self::HDR_API_VERSION] = $this->getConfig('apiVersion');
        } else {
            $headers[self::HDR_API_VERSION] = self::API_VERSION;
        }

**Comment by davidtsadler** [comment]
I will look at adding this into the version 1.0 release.  The documentation for this feature will strongly recommend that you do not rely on using this constant in your production environment and instead you should lock down your production code to a specific API. This is because updating the SDK in your environment will now change the API used by your project. Since an increase in the API version can introduce changes in how the API works, for example eBay could change the default sort order of a response, there will be the strong possibility of introducing breaking changes to your project.

In addition as changing a service API version constant will be a breaking change for the SDK I will be updating the major version number of the SDK at every update. Don't forget that some of the service versions are changed nearly every fortnight by eBay!

**Comment by davidtsadler** [comment]
Version 1.0.0 is now out. The [API Version](http://devbay.net/sdk/guides/guide/configuration.html#apiversion) is now optional.
