### ISSUE TITLE
Trading Service: Sold Items?

### ISSUE THREAD

**Issue by dustinmoore** [davidtsadler/ebay-sdk-php#174]
Since the forum link doesn't seem to work, I'll post this question here.

Is there a way via the API/SDK to find out when an item is sold so that you could subtract it from your inventory?

You have 10 of item in stock and you list the item on eBay with a quantity of 10. You sell 1 on eBay so now your inventory is at 9 and you would in theory want to reflect that on your own website/store so that someone doesn't try to buy 10 when only 9 currently exist.

**Comment by michabbb** [comment]
1) this is not the correct place, you´re right
2) a wrong place does not become the right place just because nobody answers
3) this is **NOT** a SDK question
4) it´s a regular "howto work with the ebay api" question, study the [docu](http://developer.ebay.com/devzone/xml/docs/reference/ebay/getmyebayselling.html) and use the [official ebay forum](https://forums.developer.ebay.com/)
5) if nobody answers: use the [official ebay support](https://developer.ebay.com/my/support/tickets)

beside this misplaced question: you should take a look into [notifications](https://developer.ebay.com/devzone/guides/ebayfeatures/Notifications/Notifications.html)
