### ISSUE TITLE
Catalog API - Product Based Shopping

### ISSUE THREAD

**Issue by robraux** [davidtsadler/ebay-sdk-php#192]
re: https://developer.ebay.com/api-docs/sell/static/inventory/pbse_playbook_intro.html
Are there plans to support the new Catalog API which is being required this year in order to list certain product types? The epid value will be required to list in specific categories this year. See: https://developer.ebay.com/api-docs/commerce/catalog/resources/product_summary/methods/search

I'm looking to understand if there are plans to support this in the library, and/or if someone already has a branch supporting this.

**Comment by michabbb** [comment]
till today there is no api where david said he won´t support it. i guess as long he has enough time, he is going to support this....  @davidtsadler can you give us some feedback ?

**Comment by davidtsadler** [comment]
Leave this with me. I need a few days to get up to speed with the changes that eBay are introducing and then I'll see about adding support for the Catalog API.

**Comment by michabbb** [comment]
@davidtsadler now i am at the point where i need this too. is there any other project at github u use to generate the class files ? if there would be a docu somehwere maybe we can support you here?!

**Comment by davidtsadler** [comment]
Finally got around to adding support for the Catalog API. There is a very simple [example](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/catalog/01-search.php) available.

@michabbb The SDK is still been built from the project [ebay-api-sdk-php](https://github.com/davidtsadler/ebay-api-sdk-php). I'm currently in the process of re-writing this so that that building the SDK will no longer require the eBay WSDLs or a knowledge of XSLT. The aim is to move the code generation into the SDK's repository. This will allow anyone to build the SDK.

**Comment by michabbb** [comment]
@davidtsadler you´re awesome, thanks a lot !!
