### ISSUE TITLE
issueRefund request not working properly

### ISSUE THREAD

**Issue by doralb** [davidtsadler/ebay-sdk-php#199]
Hello world, 
I am having an issue while trying to build the issueRefund function. This is the entire function

```
public function issueRefund($token, $return_request_id, $currency_id, $commnents = '', $refund_fee_type = 'PURCHASE_PRICE', $site_id = '0'){
		
	$service = new \DTS\eBaySDK\ReturnManagement\Services\ReturnManagementService([
	     'authToken' => $token,
             'credentials' => [
                'appId' => $this->appData['EBAY_APPNAME'],
                'certId' => $this->appData['EBAY_CERTNAME'],
                'devId' => $this->appData['EBAY_DEVNAME']
            ],
            'sandbox' => $this->appData['EBAY_SANDBOX'],
            'siteId' => $site_id
        ]);
		
		$request = new \DTS\eBaySDK\ReturnManagement\Types\IssueRefundRequest();
		$request->ReturnId = new DTS\eBaySDK\ReturnManagement\Types\ReturnIdType();
		$request->ReturnId->id = $return_request_id;
		
		$request->refundDetail = new DTS\eBaySDK\ReturnManagement\Types\RefundDetailType();
		$request->refundDetail->totalAmount = new DTS\eBaySDK\ReturnManagement\Types\Amount();
		$request->refundDetail->totalAmount->currencyId = $currency_id;
		
		$request->refundDetail->itemizedRefund = new DTS\eBaySDK\ReturnManagement\Types\ItemizedRefundDetailType();
		$request->refundDetail->itemizedRefund->refundFeeType = $refund_fee_type;
		$request->refundDetail->itemizedRefund->amount = new DTS\eBaySDK\ReturnManagement\Types\Amount();
		$request->refundDetail->itemizedRefund->amount->currencyId = $currency_id;
		$request->comments = $comments;
		$response = $service->issueRefund($request);
                $response = $response->toArray();
		
		if($response['Ack'] == 'Success'){
			return true;
		}
		
		return false;
		
	}
```

And I get this error : 
Exception: Invalid property type provided for itemizedRefund. Expected DTS\eBaySDK\Types\RepeatableType but got DTS\eBaySDK\ReturnManagement\Types\ItemizedRefundDetailType /home/server/application/libraries/vendor/dts/ebay-sdk-php/src/Types/BaseType.php 383

Thank you for your patiente !

**Comment by doralb** [comment]
Please can someone give some help ? :(

**Comment by michabbb** [comment]
The error sounds very clear, the framework expects a repeatable type, which is an array of something and u used something else. So instead of

$bla = [$something]

U did 

$bla = $something

Those kind of errors shouldn't happen if you a solid editor like phpstorm, because its the editors job to inform you about things like that while you are typing.

**Comment by doralb** [comment]
@michabbb  thanks for the reply. actually I am using Notepad++ and dont ask why :smile:  .... Please can you be mor specific because I gone really  devastated with this one. Maybe is way more simple than it look but...

**Comment by yiiprogrammer** [comment]
@doralb  what does $comments reference?

**Comment by yiiprogrammer** [comment]
use NetBeans it's free and is fantastic. been using it for years. or use MS Visual Studio also free. but I haven't used but is on my list to try. yep, phpstorm and jetbrains supposed to be fantastic but costs money if on a budget hehe

**Comment by michabbb** [comment]
notepadd++ ? **OMG** sorry, it´s like building a house with a pen and scissors and because you choose wrong tools, you get in trouble because of simple things like that. choos an editor that helps, none that blocks your work!

the error message is very clear:

> Invalid property type provided for itemizedRefund

[look at the ebay docu](https://developer.ebay.com/Devzone/return-management/CallRef/issueRefund.html#Request.refundDetail.itemizedRefund):

![04-06-2018-01-47-19](https://user-images.githubusercontent.com/3524595/40915836-ccd8c748-67fd-11e8-8d98-346571de3ad1.png)

what is expacted ? **_an array of_** `ItemizedRefundDetailType` and not only a single `ItemizedRefundDetailType`

but anyway: get yourself an editor that shows your mistakes like that while you type, it´s more than important especially when you are not familar with php, because your issue has nothing todo with this SDK, it´s a simple PHP question and for that, this is not the right place.

**Comment by yiiprogrammer** [comment]
Remove the "n" from $commnents =

**Comment by doralb** [comment]
@michabbb Thank you very much! @yiiprogrammer Thank you too it helped  too hahah.
