### ISSUE TITLE
Xml Parse Error: Failed to parse time string

### ISSUE THREAD

**Issue by cindicrandall** [davidtsadler/ebay-sdk-php#217]
I use getMostWatchedItems Api, But the return xml can not be correctly parsed. The error is on the timestamp.
the original timestamp node likes
<timestamp>2018-07-21T08:07:498.045Z</timestamp>
this time format can not be parsed.
Please help and advice.

**Comment by michabbb** [comment]
hi, there is no "getMostWatchedItems Api", there is only a "Merchandising API" with a call named "getMostWatchedItems". to get help, you should be more specific and help others to help you instead of confusing them 😏 

and if you don´t provide any code other people can use to reproduce your error/problem, don´t expect too much here.

**Comment by michabbb** [comment]
please close your issue
