### ISSUE TITLE
Credentials for findItemsIneBayStoresRequest

### ISSUE THREAD

**Issue by viandanteoscuro** [davidtsadler/ebay-sdk-php#271]
Hi to all!
The api call findItemsIneBayStoresRequest has a parameter RequesterCredentials, in which i must pass the auth token.
In the sdk i can't found this option, is it correct?

Thanks!

Beautiful work!

Regards

Massimo

**Comment by michabbb** [comment]
hi,

1) this project is dead
2) you should take a look [to the examples](https://github.com/davidtsadler/ebay-sdk-examples/tree/master/finding) mentioned in the README

**Comment by viandanteoscuro** [comment]
Hi,

Why this is dead?
There is another project like this well mantained?
Thanks...

**Comment by michabbb** [comment]
why? when do you see the last update? the last merge? the last comment from the owner? actually there is no really a need for a real sdk because with modern code generators you can generate all classes by yourself, I made a proof of concept and some basic tests, but it shows you, how easy it is:

https://github.com/michabbb/php-ebay-sdk
