### ISSUE TITLE
Ebay API getItem issue

### ISSUE THREAD

**Issue by tusharpragma** [davidtsadler/ebay-sdk-php#31]
I am using the getItem eBay api for finding the product itemSpecific from the UK store . I am getting all the itemSpeicifcs except the product EAN  which is default ItemSpecific . 
Here is my code : 

$request = new Types\GetItemRequestType() ;
$request->RequesterCredentials = new Types\CustomSecurityHeaderType() ;
$request->RequesterCredentials->eBayAuthToken = 'MYAUTHTOKEN' ;
$request->ItemID = 'PRODUCTID';
$request->IncludeItemSpecifics  = true ;
$request->IncludeItemCompatibilityList  = true ;

$response = $service->getItem($request) ;

is there any other option for getting the default ItemSpecifics ?

**Comment by davidtsadler** [comment]
Do you have an example item number?

**Comment by tusharpragma** [comment]
Yes.Item number : 322134970015

Regards,
Tushar
On 6/3/2016 5:37:34 PM, David Terence Sadler <notifications@github.com> wrote:
Do you have an example item number?

**Comment by davidtsadler** [comment]
I've tried getting the item using your example code and it's working for me. 

```php
foreach ($response->Item->ItemSpecifics->NameValueList as $nameValue) {
    if ($nameValue->Name === 'EAN') {
        printf("EAN found: %s\n", $nameValue->Value[0]);
    }
}
```

The one thing to keep in mind is that a seller can provide more than one value for an item specific hence why I use `$nameValue->Value[0]` in the above example.

**Comment by tusharpragma** [comment]
Sorry , i had set the custom attributes for item. Can you please try now ? Item have the defualt specific EAN , but it is not getting the specific list .

**Comment by davidtsadler** [comment]
In that case the EAN won't be found in the item specifics but in the [ProductListingDetails](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetItem.html#Response.Item.ProductListingDetails) field. For some reason the eBay documentation is not showing that the EAN field will be returned in GetItem, but it does work. 

You need to ensure that you set `DetailLevel` to either `ItemReturnAttributes` or `ReturnAll` otherwise eBay will not return the `ProductListingDetails` field.

```php
$request->DetailLevel = ['ItemReturnAttributes'];
.
.
.
printf("EAN found: %s\n", $response->Item->ProductListingDetails->EAN);
```

**Comment by tusharpragma** [comment]
Yes .It's working . Thank you .
