### ISSUE TITLE
resolution-case-management soon to be deprecated in favor of post-order

### ISSUE THREAD

**Issue by KyleFromOhio** [davidtsadler/ebay-sdk-php#38]
DEPRECATED: http://developer.ebay.com/DevZone/resolution-case-management/CallRef/getUserCases.html

Note: The Resolution Case Management API is no longer recommended. Instead, current users of the Resolution Case Management API should make plans to migrate to, and use the Return, Inquiry, and Case Management operations of the Post-Order API. New users interested is programmatically managing and resolving Item Not Received (INR) and Return/SNAD (Significantly Not as Described) cases, should also make plans to integrate with the Post-Order API. Since the Resolution Case Management API was first released, there have been many changes made to post-order flows, and Resolution Case Management API does not support all features and logic of the new flows. This API will be deprecated in the near future.

NEW: http://developer.ebay.com/Devzone/post-order/concepts/UsageGuide.html

**Comment by davidtsadler** [comment]
At the present time I have no plans to support the Post-Order API. The reason is due to been unable to obtain the WSDLs for the API. Without these I can't auto generate the required PHP classes for the SDK. It may be possible for me to code the classes manually but that will be very time consuming and at the moment I can't dedicate enough time to this task. If in the future I can get hold of the WSDLs or if I develop a means to generate the classes from the documentation, then adding the Post-Order API may be possible.
