### ISSUE TITLE
ShipmentTrackingDetails not working with unbound=true

### ISSUE THREAD

**Issue by riwale** [davidtsadler/ebay-sdk-php#49]
I didn't like batch processing of shipping ids, so i used the CompleteSale Request.

The request performs without errors but didn't update the Shipping ID and Carrier Used, only shipping time

Code used:

$shipmentType = new TradingTypes\ShipmentType();

$shipmentTrackingDetails = new TradingTypes\ShipmentTrackingDetailsType();

$shipmentTrackingDetails->ShippingCarrierUsed = $PseudoEbayShippingCarrierCode;
$shipmentTrackingDetails->ShipmentTrackingNumber = $PseudoShippingId;

$shipmentType->ShipmentTrackingDetails = $shipmentTrackingDetails;

will throw an error ("Unbound Type expected"). I have no understanding of the underlying logic behind this, but i changed "ShipmentTrackingDetails" unbound = true in ShipmentType.php to unbound = false.

Now everything works as expected!

Thank you so much for your great work!

**Comment by davidtsadler** [comment]
Change `unbound` back to `true` otherwise your copy of the SDK will be wrong. As stated in the eBay documentation the [Shipment.ShipmentTrackingDetails](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/CompleteSale.html#Request.Shipment.ShipmentTrackingDetails) field is [repeatable](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/simpleTypes.html#repeatable). This means you treat the field as an array. More information can be found the [SDK guide](http://devbay.net/sdk/guides/guide/request-and-response-objects.html#repeatable-fields-as-arrays). For future reference personal problems with the SDK should be raised the [forum](https://groups.google.com/forum/#!forum/ebay-sdk-php).
