### ISSUE TITLE
Required Product Identifiers Mandate -  Ebay Trading API changes 2017

### ISSUE THREAD

**Issue by jejeje87** [davidtsadler/ebay-sdk-php#68]
Hi, 

is there any solution to implement this new trading api requirements? 
https://developer.ebay.com/devzone/guides/ebayfeatures/Development/Listing-AnItem.html#RequiredProductIdentifiersMandate

 https://developer.ebay.com/devzone/guides/ebayfeatures/Development/Listing-AnItem.html#AddReviseRelistChanges

Thanks in advance for helping

**Comment by davidtsadler** [comment]
The SDK is generated from the WSDLs, and other sources, provided by eBay. Once eBay release the newer versions the SDK will be updated to support the new features.

**Comment by jejeje87** [comment]
Ok, so we have just to wait for the new release of the sdk. 
Thanks!!!

**Comment by davidtsadler** [comment]
Yep. Hopefully it won't be too long as rebuilding the SDK is very quick once the new WSDLs have been released.

**Comment by davidtsadler** [comment]
The 9.0.0 release of the SDK has added [partial support for the product identifiers](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Trading/Types/RecommendationsType.php#L32). The SDK should allow users to call GetCategorySpecifics in order to determine which product identifiers are available and required for a category. According the eBay documentation this will only work in the sandbox.

At the moment the SDK does not support listing items using the new way of specifying product identifiers as this information is not yet available via the WSDLs.  The [eBay release notes](https://developer.ebay.com/DevZone/XML/docs/ReleaseNotes.html#989) currently says

> The next phase of Product Identifier Mandate has been postponed until July 2017. The new schema to support the upcoming mandate has already been added to the GetCategoryFeatures call, but the functionality will only be supported in the Sandbox environment. Similarly, new schema will be added to the Add/Revise/Relist with version 997, but the functionality will only be supported in the Sandbox environment. 

Hopefully once the WSDLs have been updated I can finishing supporting this feature.

**Comment by jamesmorris7** [comment]
Hi David, If this works like I think it does, this will be an impressive tool for [looking up compatibles by MPN or product name](https://developer.ebay.com/devzone/guides/ebayfeatures/Development/CompatibleParts-Listing.html#SpecifyingPartsCompatibilitybyProduct)??
 
Is adding this as simple as adding this to my Trading types and calling it like normal, or does it need request and response files?  ( I don't know how to create request and response files yet )  ..

**Comment by davidtsadler** [comment]
Hi @jamesmorris7 I'm not sure what you are asking with regards to 

> Is adding this as simple as adding this to my Trading types and calling it like normal, or does it need request and response files? 

Can you expand on the question for me and I'll see if I can help.

**Comment by jamesmorris7** [comment]
My goal is to search parts by MPN .. I thought this script might alow that.

if it does, I'm not sure how to implement it.

**Comment by davidtsadler** [comment]
I can knock up an example of calling findProducts where the MPN is specified as the keyword in the search. Before I do I just want to check that you are aware that products in the Product service are not listings that are for sale.  findProducts will not return listings created by sellers. It returns items from eBay's product catalogue which is a repository of information that can be used when listing. For example, a seller can associate their listing with a product from the catalogue so that the fitment information is automatically filled in for the listing or the ideal category is used.

**Comment by davidtsadler** [comment]
If findProducts does return anything for an MPN keyword it may be possible to use the results of that operation to call [findItemsByProduct](http://developer.ebay.com/DevZone/finding/CallRef/findItemsByProduct.html) to get seller listings. I have not tried this so not sure how successful it will be.

**Comment by jamesmorris7** [comment]
ah!  That's actually what I want David. Your description is exactly what I
want, I have all of my part numbers, so I want to..  "associate their
listing with a product from the catalogue so that the fitment information
is automatically filled in for the listing or the ideal category is used."
... eBay motors for me.

If you mark that up, send me your PayPal and I'll shoot you a tip for your
time.

James



On Mar 2, 2017 10:57 AM, "David T. Sadler" <notifications@github.com> wrote:

I can knock up an example of calling findProducts where the MPN is
specified as the keyword in the search. Before I do I just want to check
that you are aware that products in the Product service are not listings
that are for sale. findProducts will not return listings created by
sellers. It returns items from eBay's product catalogue which is a
repository of information that can be used when listing. For example, a
seller can associate their listing with a product from the catalogue so
that the fitment information is automatically filled in for the listing or
the ideal category is used.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/davidtsadler/ebay-sdk-php/issues/68#issuecomment-283693441>,
or mute the thread

**Comment by jamesmorris7** [comment]
for clarity, I don't need to see other seller listings...
I want to create listings by using MPN to get compatibility to speed up
listing .. if that's what findProducts does.



On Mar 2, 2017 11:10 AM, "David T. Sadler" <notifications@github.com> wrote:

If findProducts does return anything for an MPN keyword it may be possible
to use the results of that operation to call findItemsByProduct
<http://developer.ebay.com/DevZone/finding/CallRef/findItemsByProduct.html>
to get seller listings. I have not tried this so not sure how successful it
will be.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/davidtsadler/ebay-sdk-php/issues/68#issuecomment-283695281>,
or mute the thread

**Comment by davidtsadler** [comment]
I'll see what I can knock up.

**Comment by jamesmorris7** [comment]
I apologize if I'm not understanding, I know your time is Super valuable
and limited ...but I believe you described what I wanted properly when you
said:

" It returns items from eBay's product catalogue which is a repository of
information that can be used when listing. For example, a seller can
associate their listing with a product from the catalogue so that the fitment
information is automatically filled in for the listing or the ideal
category is used."

**Comment by jamesmorris7** [comment]
Thanks David, there are no third-party Solution, even at an
enterprise-level, that supports compatibility for dirt bikes (without
having a franchise dealer's license.)

If this information is in eBay, this is an extremely valuable tool ... I
can't express my appreciation enough for your assistance.

**Comment by davidtsadler** [comment]
@jamesmorris7  Don't suppose you have an example MPN and eBay category ID to hand? I've never called findProducts with an MPN before, just with regular keywords such as "Brake pads" so it will be interesting to see if it works.

**Comment by davidtsadler** [comment]
The [997](https://developer.ebay.com/DevZone/XML/docs/ReleaseNotes.html#997) release of the Trading API has added support  for `ProductListingDetailsType.NameValueList` and `VariationProductListingDetailsType.NameValueList` The SDK has therefore been updated. 

Hopefully this release will allow users of the SDK to begin testing the new required product identifiers. Beware that eBay have stated

> Although the NameValueList container was added, it will not be available for use in the Sandbox environment until late in the second quarter, and not available in the Production environment until after June.
