### ISSUE TITLE
How i can get all items with full information of my seller ? 

### ISSUE THREAD

**Issue by Hoodognik** [davidtsadler/ebay-sdk-php#84]
Help me please
How i can get all items with flull information of my seller ?
I need get all products with full information and images for import to my site.
I'll try use for this GetMyeBaySellingRequestType() and i get Activelist, but list not have full information about item.

**Comment by davidtsadler** [comment]
eBay doesn't provide that many methods for obtaining a complete inventory list. You could try [GetSellerList](https://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetSellerList.html#Output) to see if that meets your needs. 

If you have any further usage questions regarding the SDK I've setup a [forum](https://forum.devbay.net/c/php-sdk) where I will try and help as best I can.

**Comment by michabbb** [comment]
@Hoodognik tip: if you have to deal with thousands of listings in your account, try to parallel this job, for example with threading, gearman, rabbitmq or amazon sqs, because you have to deal with pages. and worst of all: you don´t get *all* infos like you get it from "GetItemDetails" - so in worst case you have to do a single GetItem for every single item of "GetSellerList" btw.. if someone knows something better, please let me know ;)
